### ISSUE TITLE
500 error when changing email address on profile/edit

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#330] opened 2016-07-15 09:56 UTC
probably a duplicate to the other mailing issues, but this time on the profil edit page:

- I'm logged in on http://wheelmap.org/profile/edit and change my email to holger.dieterich+1@gmail.com or holgerdieterich@mailinator.com
- I expect to see a confirmation and get a confirmation email
- Instead, I wait for ca 30sec and then see "something went wrong"

- When I use mail@holger-dieterich.de it works: I see "E-Mail already taken" error (as expected)

**Comment by 1000miles** [comment] 2016-07-18 13:04
Yes, #330 is a duplicate of #318 and is now fixed in PR #332.

**Closed by 1000miles** 2016-07-18 13:04 UTC
