### ISSUE TITLE
SSL-Bug? Too many redirects on smartphone.php

### ISSUE THREAD

**Issue by thermann78** [sozialhelden/wheelmap#326] opened 2016-07-12 09:11 UTC
For some reason, our smartphone-switch doesn't work any more: community.wheelmap.org/smartphone.php won't open but quit with error "Could not be opened - too many redirects". I assume this comes from our switch to SSL.

Background: On our Wheelmap-Flyers we are using a QR-code leading to bit.ly/wheelmAPP, which redirects to community.wheelmap.org/smartphone.php.
This file basically catches the header and redirects.

Content of smartphone.php:

`<?php
 if (strstr($_SERVER['HTTP_USER_AGENT'],'Android')){ 
    header("location: https://market.android.com/details?id=org.wheelmap.android.online&hl=de");
  } 
  elseif (strstr($_SERVER['HTTP_USER_AGENT'],'iPhone')){
    header("location: http://itunes.apple.com/de/app/wheelmap/id399239476?mt=8"); 
  }   elseif (strstr($_SERVER['HTTP_USER_AGENT'],'iPad')){
    header("location: http://itunes.apple.com/de/app/wheelmap/id399239476?mt=8"); 
  }

  elseif (strstr($_SERVER['HTTP_USER_AGENT'],'Windows Phone')){
    header("location: https://www.microsoft.com/de-de/store/apps/wheelmap/87njfdsnjkfds"); 
  } 
 
   else{
    header("location: http://blog.wheelmap.org/was-ist-wheelmap/#smartphones");
  }
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Wheelmap.org - Weiterleitung</title>

</head>

<body>
<h1>Weiterleitung</h1>
Sie werden automatisch weitergeleitet. Sollte die Weiterleitung nicht funktionieren, klicken Sie bitte <a href="http://blog.wheelmap.org/was-ist-wheelmap/#smartphones">hier</a>.
</body>
</html>`

This should be fixed soon as the QR on our flyers is a direct contact option.

**Comment by holgerd** [comment] 2016-08-01 07:27
lets have a look at this after we've moved to the new server (next week)

**Comment by Xylakant** [comment] 2016-09-07 13:26
this is unrelated to the app servers. It looks like the ssl setup for community.wordpress.org is somewhat messed up: https://community.wheelmap.org/ goes to pfandtastisch helfen.

**Comment by Xylakant** [comment] 2016-09-07 15:58
so the bug seems to be that as long as we're not using "ssl mode: full" or better the backend connection to the wordpress server is not encrypted and then the wordpress ignores the header that CF uses to indicate that the browser indeed used https and wants to redirect to https - an infinite loop.

If I enable ssl mode "full" then community.wheelmap.org delivers the wrong content. (pfandtastisch...)

**Comment by Svenyo** [comment] 2016-09-07 16:13
@holgerd @thermann78 What do we need to fix this? Jonas will be running around in Rio spreading our flyers soon. :-D

**Comment by 1000miles** [comment] 2016-09-08 08:45
I did some tests today (2016, sept 8) and that is what I experience from my side:

**mac desktop**
- when i call `bit.ly/wheelmAPP` in the browser, i get redirected to `https://community.wheelmap.org/about/#smartphones` 

**android**
- when i call `bit.ly/wheelmAPP` in the browser, i get redirected to `play.google.com` (google play store) to install the app on my android
- when i call `community.wheelmap.org/smartphone.php` in the browser, i get redirected to `play.google.com` (google play store) to install the app on my android


**iphone**
- when i call `bit.ly/wheelmAPP` in the browser, i get redirected to the apple store to install the app on my iphone
- when i call `community.wheelmap.org/smartphone.php` in the browser, i get redirected to the apple store to install the app on my iphone

Conclusion: 
I can not reproduce mentioned error message `Could not be opened - too many redirects` as of today. Has anyone fixed this issue meanwhile?

**Comment by Xylakant** [comment] 2016-09-08 09:33
well, if it's fixed, let's close it.

**Closed by Xylakant** 2016-09-08 09:33 UTC
Labels: bug, in progress

**Comment by holgerd** [comment] 2016-09-12 11:19
For documentation:
We could reproduce this "too many redirects" behavior only in the iOS App https://itunes.apple.com/de/app/qr-reader-for-iphone/id368494609?mt=8 . It worked in the App RedLaser for example.

Anyways, I will change the bitly link to directly go to the new php file (waiting for Andi for the bitly login)

**Comment by Xylakant** [comment] 2016-09-12 11:24
it was reproducible for all clients before. The smartphone.php tries to match on the user agent, maybe the app sends an unexpected one.

in any case: I think it would be best to move the code in the smartphone.php to the rails app. That's much easier to handle an one level of indirection less.

**Comment by 1000miles** [comment] 2016-09-12 11:38
We will create a follow up ticket for this to keep this ticket closed.
