### ISSUE TITLE
POIs wrongly show up in Taubenstrasse Berlin

### ISSUE THREAD

**Issue by AllroadsNL** [sozialhelden/wheelmap#586] opened 2017-03-04 18:21 UTC
There a lot of poi on the same place in Berlin
https://www.openstreetmap.org/#map=20/52.51296/13.38804&layers=H

One of the poi:
https://www.openstreetmap.org/changeset/46569750
http://overpass-api.de/achavi/?changeset=46569750

From Dutch forum;
https://forum.openstreetmap.org/viewtopic.php?pid=634801#p634801

Looks like wheelmap put all poi in one place.

A bug?

**Comment by AllroadsNL** [comment] 2017-03-05 13:39
These are important POI, **they can not be deleted**, and must be in placed as soon as possible on the good position, before others set new POI on the same spot.

The bug must be solved immediately.

**Comment by holgerd** [comment] 2017-03-06 11:46
Hi AllroadsNL, thanks for your report!

## Status
My hypothesis today is that it is a bug in the current Wheelmap iOS version which causes newly added places to show up at Taubenstraße.

## Suggested next steps

### Regarding the bug
1. Get confirmation from the agency who built the app to reproduce the bug and come up with a fix
2. Update the app and put them in the App Store
3. Monitor the Taubenstrasse area weekly and if it happens again contact each affected OSM contributor what iOS app they were using.

### Regarding the wrong nodes already in OSM
1.  Move the wrong nodes to the correct position where address is given (or the name is unique enough to be found on the web)
2. contact the contributors for places with too few information and ask for help finding them
3. If no reply, delete these last nodes.

## Background
We had a bug in an old version of the Wheelmap iOS app and fixed it with an update in September 2016. We still saw the bug but concluded it was due to people who used the old version of the iOS app. That's why we decided to clean up bi-weekly and contact each OSM-user and ask them to update the app until no more new places appeared (we cannot pull the old iOS version from people's phones).

I analysed this again now and found out that our hypothesis was wrong. The bug still appears in the current version of our iOS app, but only in rare cases we could not reproduce yet. I contacted the agency who built the Wheelmap iOS app and will ask them to comment here as well.

## Log of wrong places ca. March 4-6, 2017
I looked with the iD editor at the spot at Taubenstrasse and found these wrongly located places from last weekend:

by https://www.openstreetmap.org/user/LeoclubGouda
https://www.openstreetmap.org/node/4716308592/history
https://www.openstreetmap.org/node/4716305598/history
https://www.openstreetmap.org/node/4716344589/history
https://www.openstreetmap.org/node/4716313595/history
https://www.openstreetmap.org/node/4716333193/history
https://www.openstreetmap.org/node/4716322091/history
https://www.openstreetmap.org/node/4716322296/history
https://www.openstreetmap.org/node/4716306094/history
https://www.openstreetmap.org/node/4716438889/history
https://www.openstreetmap.org/node/4716349989/history


by https://www.openstreetmap.org/user/Jihanna
https://www.openstreetmap.org/node/4716540192/history
https://www.openstreetmap.org/node/4716609991/history
https://www.openstreetmap.org/node/4716600990/history
https://www.openstreetmap.org/node/4716658492/history
https://www.openstreetmap.org/node/4716566592/history
https://www.openstreetmap.org/node/4716609992/history
https://www.openstreetmap.org/node/4716630192/history
https://www.openstreetmap.org/node/4716642090/history
https://www.openstreetmap.org/node/4716602301/history
https://www.openstreetmap.org/node/4716543098/history
https://www.openstreetmap.org/node/4716535492/history
https://www.openstreetmap.org/node/4716645092/history
https://www.openstreetmap.org/node/4716305598/history
https://www.openstreetmap.org/node/4716630189/history
https://www.openstreetmap.org/node/4716616991/history
https://www.openstreetmap.org/node/4716602289/history
https://www.openstreetmap.org/node/4716543191/history
https://www.openstreetmap.org/node/4716567990/history
https://www.openstreetmap.org/node/4716648090/history
https://www.openstreetmap.org/node/4716609989/history


by https://www.openstreetmap.org/user/Siannath
https://www.openstreetmap.org/node/4715861589/history


by https://www.openstreetmap.org/user/drangelicus
https://www.openstreetmap.org/node/4716336193/history


by https://www.openstreetmap.org/user/ElliMeyer
https://www.openstreetmap.org/node/4713211590/history

**Comment by holgerd** [comment] 2017-03-06 13:06
related: #439

**Comment by holgerd** [comment] 2017-03-07 08:29
Update: When I disallow location/GPS for the Wheelmap iOS app, Taubenstraße is assumed as default. It seems some users do not understand that lat/lon positioning requires to drag the marker in this screen:

![img_7706](https://cloud.githubusercontent.com/assets/218506/23647896/8c206486-0318-11e7-9514-e9a84a5411fe.PNG)

I'm in discussion with the App agency to find a way to resolve this.

**Comment by 1000miles** [comment] 2017-03-22 13:48
As agreed with Holger today we are assigning this ticket to @holgerd since this issue seems to be fixed for now.

**Comment by holgerd** [comment] 2017-03-22 14:02
Yes, we found a bug in the iOS app, fixed it and published it on the App store last Monday (March 20).

When a user adds a new node using the iOS app s/he is presented with a map of their surrounding, so s/he can put the pin exactly where the new node will be. In many cases, the pin did not need to be moved because the person already was right at the place. In that case, the app falsely put the node in Taubenstraße instead of the assigned place. We're very happy to have found a reproducible bug at last and hope this fixes this issue.

We are moving the wrongly added places from Taubenstraße and hope no new ones will show up.

Sorry that this happened and thank you all for taking the time to explain us the problem and help research the cause.

**Closed by holgerd** 2017-03-22 14:02 UTC
