### ISSUE TITLE
wrong redirect https://community.wheelmap.org/de

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#151] opened 2016-02-18 08:56 UTC
- I type wheelmap.de or www.wheelmap.de in my broswer window
- I excpect this to forward to wheelmap.org
- Instead, I get redirected to https://community.wheelmap.org/der-social-day-2015-mit-immobilienscout24/

**Comment by thermann78** [comment] 2016-02-18 09:07
This is known and included in Issue #51 as it results from wrong Nginx configuration as described within the listed issue.

**Comment by holgerd** [comment] 2016-02-18 09:25
When I check the http header for http://wheelmap.org/de I get this result:

http://wheelmap.org/de
301 Moved Permanently
https://community.wheelmap.org/de
301 Moved Permanently
https://community.wheelmap.org/der-social-day-2015-mit-immobilienscout24/
200 OK

As far as I understand it, the first redirect ist coming from #51 but the second is a different problem, hence the this issue. My guess is that wordpress "auto-completes" the URL from "/de" to /der-social-day-2015-mit-immobilienscout24/"?

**Comment by holgerd** [comment] 2016-02-18 09:32
>>> http://wheelmap.org/de

> --------------------------------------------
> 301 Moved Permanently
> --------------------------------------------

Status:	301 Moved Permanently
Code:	301
Date:	Thu, 18 Feb 2016 09:20:55 GMT
Content-Type:	text/html; charset=iso-8859-1
Connection:	close
Set-Cookie:	__cfduid=df71c55058a65a441061a46ff91ab739f1455787255; expires=Fri, 17-Feb-17 09:20:55 GMT; path=/; domain=.wheelmap.org; HttpOnly
Location:	https://community.wheelmap.org/de
Cache-Control:	max-age=43200
Expires:	Thu, 18 Feb 2016 21:20:52 GMT
Server:	cloudflare-nginx
CF-RAY:	2768a8a8dd612726-FRA




>>> https://community.wheelmap.org/de

> --------------------------------------------
> 301 Moved Permanently
> --------------------------------------------

Status:	301 Moved Permanently
Code:	301
Server:	cloudflare-nginx
Date:	Thu, 18 Feb 2016 09:20:56 GMT
Content-Type:	text/html; charset=UTF-8
Connection:	close
Set-Cookie:	_icl_current_language=de; expires=Fri, 19-Feb-2016 09:20:53 GMT; Max-Age=86400; path=/
X-Powered-By:	PHP/5.5.30
Expires:	Wed, 11 Jan 1984 05:00:00 GMT
Cache-Control:	no-cache, must-revalidate, max-age=0
Pragma:	no-cache
Vary:	Accept-Encoding,User-Agent
Location:	https://community.wheelmap.org/der-social-day-2015-mit-immobilienscout24/
CF-RAY:	2768a8a9cffd275c-FRA




>>> https://community.wheelmap.org/der-social-day-2015-mit-immobilienscout24/

> --------------------------------------------
> 200 OK
> --------------------------------------------

Status:	200 OK
Code:	200
Server:	cloudflare-nginx
Date:	Thu, 18 Feb 2016 09:20:56 GMT
Content-Type:	text/html
Connection:	close
Set-Cookie:	__cfduid=d24a63b139c093d186cf7cc55767e9c771455787256; expires=Fri, 17-Feb-17 09:20:56 GMT; path=/; domain=.wheelmap.org; HttpOnly
X-Powered-By:	PHP/5.5.30
Expires:	Thu, 18 Feb 2016 21:20:53 GMT
Vary:	Accept-Encoding,User-Agent
Last-Modified:	Thu, 01 Jan 1970 00:00:00 GMT
CF-RAY:	2768a8b0ee6f2654-FRA

**Comment by thermann78** [comment] 2016-02-18 10:06
Yeah, this is normal behaviour by WordPress. The core tries to autocomplete URLs that couldn't be matched directly with a permalink. It's not a bug, but a feature.
The failure results from a false config: wheelmap.de redirects, as descripted above, to wheelmap.org/de - a directory that doesn't exist. This happens as followed:

1. All requests hit our App-Server who calls its Nginx-Conf.
2. If there is no match with any URL existing on the App-Server the request will be proxied to our WordPress-vServer.
3. WP catches the request and tries to auto-complete it.

The correct redirect path for wheelmap.de is just wheelmap.org as German is the default language - there is no subdirectory for /de.
In many other cases there are also some malconfigurations redirecting e.g. gr.wheelmap.org to wheelmap.org/gr - correct path would be wheelmap.org/map/gr.

**Comment by holgerd** [comment] 2016-02-18 10:09
okay.

**Comment by lennerd** [comment] 2016-02-19 09:54
I would like to reopen this. This redirect is clearly a problem of the nginx configuration. Let me explain this via the example of Holger in https://github.com/sozialhelden/wheelmap/issues/151#issuecomment-185623315:

> http://wheelmap.org/de
301 Moved Permanently
https://community.wheelmap.org/de
301 Moved Permanently
https://community.wheelmap.org/der-social-day-2015-mit-immobilienscout24/
200 OK

@thermann78 Yes, Wordpress is trying to fix the `/de` path name part of the URL. But: The nginx server configuration is redirecting first to the http://wheelmap.org/de and than to https://community.wheelmap.org/de. Or not? I think this needs to be fixed server side.

**Comment by thermann78** [comment] 2016-02-19 10:04
Right, but as written above: this is part of #51 :) That's why @holgerd closed it.

**Comment by lennerd** [comment] 2016-02-19 11:11
Ah sorry.

**Closed by lennerd** 2016-02-19 11:11 UTC
Labels: bug
