### ISSUE TITLE
[Airbrake] NotChanged

### ISSUE THREAD

**Issue by thermann78** [sozialhelden/wheelmap#191] opened 2016-04-16 21:16 UTC
**Airbrake error:** [#6784](https://wheelmap.airbrake.io/projects/13709/groups/1568031200580786784)
**Airbrake project:** wheelmap

**Error type:** `Rosemary::Conflict`
**Error message:** `` NotChanged ``
**Where:** `UpdateTagsJob#perform`
**Occurred at:** Apr 16, 2016 21:15:10 UTC
**First seen at:** Dec 04, 2015 11:18:05 UTC
**Occurrences:** 16759 (564 since last deploy on Apr 13, 2016 09:29:04 UTC)

**URL:** `<no information>`
**File:** `app/jobs/update_tags_job.rb`

**Backtrace:**
```
app/jobs/update_tags_job.rb:50:in perform
/gems/delayed_job-4.1.1/lib/delayed/backend/base.rb:100:in block in invoke_job
/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:61:in call
/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:61:in block in initialize
```

**Comment by holgerd** [comment] 2016-04-16 21:18
This issue was created by me (not timo) while browsing airbrake. Let's discuss this on Monday @1000miles @Xylakant

**Comment by 1000miles** [comment] 2016-04-18 08:01
@holgerd Thanks for the info. Yes, let's talk later.

P.S. I think this ticket is a duplicate of this, or? https://github.com/sozialhelden/wheelmap/issues/184

**Comment by holgerd** [comment] 2016-05-03 07:54
yes, duplicate.

**Closed by holgerd** 2016-05-03 07:54 UTC
Labels: airbrake, in progress
