### ISSUE TITLE
Some markers not showing up, some detail sites not loading

### ISSUE THREAD

**Issue by thermann78** [sozialhelden/wheelmap#57] opened 2015-11-11 10:50 UTC
Important: new bug first seen at nov 6th, since then more then 8k occurences!
Error type: Sprockets::Helpers::RailsHelper::AssetPaths::AssetNotPrecompiledError
Error message: Sprockets::Helpers::RailsHelper::AssetPaths::AssetNotPrecompiledError: [#<ProvidedPoi id: 14278, poi_id: 429739180, provider_id: 3, wheelchair: "limited", url: nil, created_at: "2014-10-03 01:12:35", updated_at: "2014-10-03 01:12:35", wheelchair_toilet: nil>] isn't precompiled

Occurs on map when a marker image won't be loaded, when clicked on detail site a ruby error appears.
https://wheelmap.airbrake.io/projects/13709/groups/1547716226226638860/notices/1551345795529759116

**Comment by joustava** [comment] 2015-11-13 18:25
From a quick glance, this seems to be caused by:

https://github.com/sozialhelden/wheelmap/blob/7a773349ab5a207b6c218a224ea6d12e9dc66e3f/app/views/nodes/_node_map.html.haml#L8

which uses

https://github.com/sozialhelden/wheelmap/blob/7a773349ab5a207b6c218a224ea6d12e9dc66e3f/app/models/poi.rb#L307

sponsor returns a provided_pois instead of a single path. This piece of code doesn't have test coverage at all so I do not know its intended use, I can only assume it should  search for the first available logo url. Sprockets::Helpers::RailsHelper::AssetPaths::AssetNotPrecompiledError occurs because it cannot handle the object.

**Comment by lennerd** [comment] 2015-11-13 18:27
Thanks for digging. I will take a look as soon as I can. Maybe I'm able to fix this. If someone from Asquera is able to fix this, this would be great.

**Comment by lennerd** [comment] 2015-11-16 09:25
@thermann78 Do you maybe have a link for a detail page not working anymore?

**Comment by thermann78** [comment] 2015-11-16 09:46
http://wheelmap.org/nodes/429739180
-- 
Timo Hermann
SOZIALHELDEN e.V.
c/o Immobilien Scout GmbH, Andreasstraße 10, 10243 Berlin

E-Mail: timo@sozialhelden.de <mailto:timo@sozialhelden.de>
Web: http://www.sozialhelden.de <http://www.sozialhelden.de/>

SOZIALHELDEN @ facebook <http://www.facebook.com/SOZIALHELDEN> - twitter <http://twitter.com/#%21/SOZIALHELDEN> - flickr <http://www.flickr.com/photos/sozialhelden/> - YouTube <http://www.youtube.com/user/sozialhelden> - betterplace.org <http://www.betterplace.org/de/organisations/sozialhelden_ev>
Spendenkonto: 
SOZIALHELDEN e.V. 
GLS Gemeinschaftsbank eG
BLZ: 43060967 
Kto: 1000200000

**Comment by joustava** [comment] 2015-11-16 10:46
@christoph-buente do you have any ideas about this https://github.com/sozialhelden/wheelmap/issues/57#issuecomment-156509260

**Comment by lennerd** [comment] 2015-11-16 11:25
He is in New York right now. I'm lookin into this in the afternoon I hope.

**Comment by lennerd** [comment] 2015-11-16 12:56
We already fixed it but haven't merged our fix to production yet. Deployed again. Everything should work fine again.

**Closed** 2015-11-16 12:55 UTC
